export const sagaActions = {
  FETCH_PRODUCTS: 'FETCH_PRODUCTS',
  FETCH_PRODUCTS_CATEGORY: 'FETCH_PRODUCTS_CATEGORY',
  FETCH_PRODUCTS_BY_CATEGORY: 'FETCH_PRODUCTS_BY_CATEGORY',
  USER_LOGIN: 'USER_LOGIN',
};
